services:
    rpp:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rpp
        restart: unless-stopped
        volumes:
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
            - ./maps:/app/maps
        env_file:
            - .env
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
