# fly.toml app configuration file generated for rustplusplus-bvlzrg on 2025-03-20T11:01:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rustplusplus-bvlzrg'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
