module.exports = {
    Monument: {
        'AbandonedMilitaryBase': 'Abandoned Military Base',
        'airfield_display_name': 'Airfield',
        'arctic_base_a': 'Arctic Research Base',
        'bandit_camp': 'Bandit Camp',
        'dome_monument_name': 'The Dome',
        'excavator': 'Giant Excavator Pit',
        'fishing_village_display_name': 'Fishing Village',
        'gas_station': "Oxum's Gas Station",
        'harbor_2_display_name': 'Harbor',
        'harbor_display_name': 'Harbor',
        'junkyard_display_name': 'Junkyard',
        'large_fishing_village_display_name': 'Large Fishing Village',
        'large_oil_rig': 'Large Oil Rig',
        'launchsite': 'Launch Site',
        'lighthouse_display_name': 'Lighthouse',
        'military_tunnels_display_name': 'Military Tunnel',
        'mining_outpost_display_name': 'Mining Outpost',
        'mining_quarry_hqm_display_name': 'HQM Quarry',
        'mining_quarry_stone_display_name': 'Stone Quarry',
        'mining_quarry_sulfur_display_name': 'Sulfur Quarry',
        'oil_rig_small': 'Oil Rig',
        'outpost': 'Outpost',
        'power_plant_display_name': 'Power Plant',
        'satellite_dish_display_name': 'Satellite Dish',
        'sewer_display_name': 'Sewer Branch',
        'stables_a': 'Ranch',
        'stables_b': 'Large Barn',
        'supermarket': 'Abandoned Supermarket',
        'swamp_c': 'Abandoned Cabins',
        'train_tunnel_display_name': '',
        'train_yard_display_name': 'Train Yard',
        'underwater_lab': 'Underwater Lab',
        'water_treatment_plant_display_name': 'Water Treatment Plant'
    },
}