module.exports = {
    Monument: {
        AbandonedMilitaryBase: { clean: 'Abandoned Military Base', map: 'ABANDONED MILITARY BASE' },
        airfield_display_name: { clean: 'Airfield', map: 'AIRFIELD' },
        arctic_base_a: { clean: 'Arctic Research Base', map: 'ARCTIC RESEARCH BASE' },
        bandit_camp: { clean: 'Bandit Camp', map: 'BANDIT CAMP' },
        dome_monument_name: { clean: 'The Dome', map: 'THE DOME' },
        excavator: { clean: 'Giant Excavator Pit', map: 'GIANT EXCAVATOR PIT' },
        fishing_village_display_name: { clean: 'Fishing Village', map: 'FISHING VILLAGE' },
        gas_station: { clean: "Oxum's Gas Station", map: 'OXUM\'S GAS STATION' },
        harbor_2_display_name: { clean: 'Harbor', map: 'HARBOR' },
        harbor_display_name: { clean: 'Harbor', map: 'HARBOR' },
        junkyard_display_name: { clean: 'Junkyard', map: 'JUNKYARD' },
        large_fishing_village_display_name: { clean: 'Large Fishing Village', map: 'LARGE FISHING VILLAGE' },
        large_oil_rig: { clean: 'Large Oil Rig', map: 'LARGE OIL RIG' },
        launchsite: { clean: 'Launch Site', map: 'LAUNCH SITE' },
        lighthouse_display_name: { clean: 'Lighthouse', map: 'LIGHTHOUSE' },
        military_tunnels_display_name: { clean: 'Military Tunnel', map: 'MILITARY TUNNEL' },
        mining_outpost_display_name: { clean: 'Mining Outpost', map: 'MINING OUTPOST' },
        mining_quarry_hqm_display_name: { clean: 'HQM Quarry', map: 'HQM QUARRY' },
        mining_quarry_stone_display_name: { clean: 'Stone Quarry', map: 'STONE QUARRY' },
        mining_quarry_sulfur_display_name: { clean: 'Sulfur Quarry', map: 'SULFUR QUARRY' },
        oil_rig_small: { clean: 'Oil Rig', map: 'OIL RIG' },
        outpost: { clean: 'Outpost', map: 'OUTPOST' },
        power_plant_display_name: { clean: 'Power Plant', map: 'POWER PLANT' },
        satellite_dish_display_name: { clean: 'Satellite Dish', map: 'SATELLITE DISH' },
        sewer_display_name: { clean: 'Sewer Branch', map: 'SEWER BRANCH' },
        stables_a: { clean: 'Ranch', map: 'RANCH' },
        stables_b: { clean: 'Large Barn', map: 'LARGE BARN' },
        supermarket: { clean: 'Abandoned Supermarket', map: 'ABANDONED SUPERMARKET' },
        swamp_c: { clean: 'Abandoned Cabins', map: 'ABANDONED CABINS' },
        train_tunnel_display_name: { clean: '', map: '' },
        train_yard_display_name: { clean: 'Train Yard', map: 'TRAIN YARD' },
        underwater_lab: { clean: 'Underwater Lab', map: 'UNDERWATER LAB' },
        water_treatment_plant_display_name: { clean: 'Water Treatment Plant', map: 'WATER TREATMENT PLANT' }
    },
}